#ifndef _NIGHT_ERROR_CODES_H_
#define _NIGHT_ERROR_CODES_H_

typedef enum _NightcoreErrorCodes
{
    SUCCESS,
    ERROR_INVALID_INPUT_FILE_PATH,
    ERROR_INVALID_OUTPUT_FILE_PATH,
    ERROR_INVALID_INPUT_EXTENSION,
    ERROR_INVALID_OUTPUT_EXTENSION,
    ERROR_CANT_CREATE_ALL_ELEMENTS,
    ERROR_CANT_LINK_ALL_ELEMENTS,
    ERROR_NULL_POINTER,
    ERROR_INVALID_VALUE_RANGE,
    ERROR_CANT_SET_PIPELINE_PLAYING,
    ERROR_INVALID_THUMBNAIL_EXTENSION
}NightcoreErrorCodes;



#endif